### PR TITLE
AgentSpawner refactor, Removed Agent Context, Better naming with namespaces to avoid repeating names

### PR DESCRIPTION
**Pull request by Windings-Lab**

### CODE REVIEW

**Comment by mororo250** [comment]
How many contexts should we have? Should agent really be in a different context? 
Doesn't make sense to have components shared among Agent, Items and particles for example? Like position, sprite, etc.
Don't we kill the whole purpose of ecs by having too many contexts?  
@Windings-Lab Why should inventory be in its own context? This means that I can't add inventory to an agent anymore.

**Comment by Windings-Lab** [comment]
> How many contexts should we have? Should agent really be in a different context? Doesn't make sense to have components shared among Agent, Items and particles for example? Like position, sprite, etc. Don't we kill the whole purpose of ecs by having too many contexts? @Windings-Lab Why should inventory be in its own context? This means that I can't add inventory to an agent anymore.

Wait, really? Let me test this. I though we can add Inventory even out of the context

**Comment by mororo250** [comment]
Reference: https://mzaks.medium.com/why-components-need-different-context-types-in-entitas-csharp-e12e0aee9a67

**Comment by zoubirabde9a** [comment]
We need to have 1 context per planet, but for now we will only have 1 context

**Comment by haltingstate** [comment]
>How many contexts should we have? Should agent really be in a different context?

Single context for game, for now.

Each planet might be own context eventually. But not necessary right now.

**Pull request merged**
